### ISSUE TITLE
StLouis county data for 8/13 has no new cases for any zip code. Why?

### ISSUE THREAD

**Issue by lgfelton** [slu-openGIS/MO_HEALTH_Covid_Tracking#4]
Was there no data to load or was the server down?

**Comment by chris-prener** [comment]
hi @lgfelton - I believe they did not update their data, or if they did it was after my evening update.

**Comment by lgfelton** [comment]
Thank you!
Larry
    On Sunday, August 15, 2021, 02:51:51 PM CDT, Christopher Prener ***@***.***> wrote:  
 
 


hi @lgfelton - I believe they did not update their data, or if they did it was after my evening update.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
