### ISSUE TITLE
Jefferson County Zip for 9-13

### ISSUE THREAD

**Issue by lgfelton** [slu-openGIS/MO_HEALTH_Covid_Tracking#5]
The numbers for total cases and new cases seem to be reversed.

**Comment by chris-prener** [comment]
Thanks for flagging that. They're not reversed... they seem to have restarted counting maybe? I'm going to do some more digging tonight and see what I can figure out.

**Comment by chris-prener** [comment]
I've fixed the workflow issue - they switched to reporting active cases but are still tabulating cumulative cases (and just not exposing those counts on the dashboard map). The website will reflect the right counts tomorrow.
