### ISSUE TITLE
Dec 3 update

### ISSUE THREAD

**Issue by lgfelton** [slu-openGIS/MO_HEALTH_Covid_Tracking#6]
Just wondered why there was no update for Dec. 3

**Comment by chris-prener** [comment]
It didn't get pushed by my script for some reason. Sorry about that. The 3rd and the 4th will be uploaded shortly.

**Comment by chris-prener** [comment]
All should be available now @lgfelton!

**Comment by lgfelton** [comment]
No problem.I apprecate the effort from you and your team.LarrySent via the Samsung Galaxy S10+, an AT&T 5G Evolution capable smartphone
-------- Original message --------From: Christopher Prener ***@***.***> Date: 12/4/21  6:44 PM  (GMT-06:00) To: slu-openGIS/MO_HEALTH_Covid_Tracking ***@***.***> Cc: lgfelton ***@***.***>, Author ***@***.***> Subject: Re: [slu-openGIS/MO_HEALTH_Covid_Tracking] Dec 3 update (Issue #6) 
It didn't get pushed by my script for some reason. Sorry about that. The 3rd and the 4th will be uploaded shortly.
